### ISSUE TITLE
Unexpected Keyword Argument 'lr_u'

### ISSUE THREAD

**Issue by pratyushmaini** [shengliu66/SOP#6]
I was running the code out of the box and encounter this error while loading the SGD module parameters.

```
Traceback (most recent call last):
  File "SOP/train.py", line 142, in <module>
    main(config)
  File "SOP/train.py", line 89, in main
    optimizer_overparametrization = config.initialize('optimizer_overparametrization', torch.optim, reparam_params)
  File "SOP/parse_config.py", line 94, in initialize
    return getattr(module, module_name)(*args, **module_args)
TypeError: __init__() got an unexpected keyword argument 'lr_u'
```

**Comment by shengliu66** [comment]
Thank you for pointing out this, we have been modifying the code these days to make it easier to read, we should have the updated version at the end of this week.

**Comment by shengliu66** [comment]
Done, please let me know if there is any issues

**Comment by pratyushmaini** [comment]
Thanks!
